### PR TITLE
Add affiliation to duncan-tree-zhou

### PR DESCRIPTION
**Pull request by Duncan-tree-zhou**
could you help to add me duncan-tree-zhou to the list?

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
There is no such GitHub user: https://github.com/duncantreezhou - so I cannot do this update.
I'll change to `Duncan-tree-zhou`.

**Comment by Duncan-tree-zhou** [comment]
do I need to raise another PR?

**Comment by lukaszgryglicki** [comment]
No, I just did manual updates but didn't pushed yet, I'm doing some other updates as well and then will push all of them.
This was just FYI.

**Pull request merged**
