### PR TITLE
Add affiliation for @AmbrishRamachandiran @krishnakv

### PR DESCRIPTION
**Pull request by AmbrishRamachandiran**
add affiliation for [krishnakv](https://github.com/krishnakv) , [AmbrishRamachandiran](https://github.com/AmbrishRamachandiran)

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by AmbrishRamachandiran** [comment]
@lukaszgryglicki 
[Developer Activity Counts by Companies](https://all.devstats.cncf.io/d/66/developer-activity-counts-by-companies?var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=Infosys%20Limited)

In over all cncf still my profile is not visible any possible reason?

**Comment by lukaszgryglicki** [comment]
Yes, PR was merged 2 weeks ago and data is imported once per 28 days.
If it is still not there after 28 days passed, LMK, I'll check and if there is any reason that it is not there, I'll import and regenerate data manually toi make sure all is reflected.

**Comment by AmbrishRamachandiran** [comment]
> Yes, PR was merged 2 weeks ago and data is imported once per 28 days.
> 
> If it is still not there after 28 days passed, LMK, I'll check and if there is any reason that it is not there, I'll import and regenerate data manually toi make sure all is reflected.
> 
> 

@lukaszgryglicki the profiles are still not updated in over all cncf devstats can you please add them manually?



Add these profiles too manually 


https://github.com/cncf/gitdm/pull/264

https://github.com/cncf/gitdm/pull/274

**Comment by lukaszgryglicki** [comment]
I will take a look on Friday and during the weekend.

**Comment by lukaszgryglicki** [comment]
There is still no bug here, will be importing manually, note that `All CNCF` affiliations are imported 28th of each month while the PR was merged on 29th: https://github.com/cncf/gitdm/pull/258#event-11621803509, see schedule: https://github.com/cncf/devstats-helm/blob/master/devstats-helm/values.yaml#L1212
Anyway, will make sure all is imported on Friday or during the weekend.

**Comment by AmbrishRamachandiran** [comment]
> There is still no bug here, will be importing manually, note that `All CNCF` affiliations are imported 28th of each month while the PR was merged on 29th: [#258 (comment)](https://github.com/cncf/gitdm/pull/258#event-11621803509), see schedule: https://github.com/cncf/devstats-helm/blob/master/devstats-helm/values.yaml#L1212 Anyway, will make sure all is imported on Friday or during the weekend.

Just checked the data are updated now thanks for your support

**Comment by lukaszgryglicki** [comment]
ohhh is it?
Right, the import finished yesterday.... (2nd line 22 hours ago).
```
root@devstats-node-2:~/go/src/github.com/cncf/devstats-k8s-lf/util# k get po -A | grep devstats-affiliations-all
devstats-prod    devstats-affiliations-all-1706342400-8n5bm                       0/1     Completed   0          31d
devstats-prod    devstats-affiliations-all-1709020800-ch9hr                       0/1     Completed   0          22h
devstats-prod    devstats-affiliations-allcdf-1707283860-qsfjz                    0/1     Completed   0          21d
devstats-test    devstats-affiliations-allcdf-1705815720-gznxt                    0/1     Completed   0          38d
devstats-test    devstats-affiliations-allcdf-1708494120-5czmd                    0/1     Completed   0          7d
```


And:
```
2024-02-27 15:29:11 all/gha2db_sync: columns
2024-02-27 15:30:09 all/gha2db_sync: columns ... 57.482705992s
2024-02-27 15:30:09 all/gha2db_sync: vars
2024-02-27 15:30:09 all/gha2db_sync: Environment Override: map[GHA2DB_VARS_FN_YAML:sync_vars.yaml]
2024-02-27 15:30:34 all/gha2db_sync: vars ... 25.610909091s
2024-02-27 15:30:34 all/gha2db_sync: Sync success
2024-02-27 15:30:34 all/gha2db_sync: gha2db_sync.go: error closing the connection: write tcp 192.168.193.218:53216->192.168.193.209:5432: write: broken pipe, sleeping for 300s to retry
2024-02-27 15:35:34 all/gha2db_sync: Time: 7h23m55.867787426s
setting provisioned flag on 'allprj' database
INSERT 0 1
database 'allprj' marked as provisioned
All affiliations updated
Exit handler, final status is '0'
setting provisioned flag on 'allprj' database
INSERT 0 0
database 'allprj' marked as provisioned
clearing affs_lock flag on 'allprj' database
DELETE 1
database 'allprj' affs_lock flag cleared
clearing affs_lock_all flag on 'devstats' database
DELETE 1
database 'devstats' affs_lock_all flag cleared

```


Just LMK then if there is still any action needed for Friday/weekend?

**Comment by AmbrishRamachandiran** [comment]
> ohhh is it? Right, the import finished yesterday.... (2nd line 22 hours ago).
> 
> ```
> root@devstats-node-2:~/go/src/github.com/cncf/devstats-k8s-lf/util# k get po -A | grep devstats-affiliations-all
> devstats-prod    devstats-affiliations-all-1706342400-8n5bm                       0/1     Completed   0          31d
> devstats-prod    devstats-affiliations-all-1709020800-ch9hr                       0/1     Completed   0          22h
> devstats-prod    devstats-affiliations-allcdf-1707283860-qsfjz                    0/1     Completed   0          21d
> devstats-test    devstats-affiliations-allcdf-1705815720-gznxt                    0/1     Completed   0          38d
> devstats-test    devstats-affiliations-allcdf-1708494120-5czmd                    0/1     Completed   0          7d
> ```
> 
> And:
> 
> ```
> 2024-02-27 15:29:11 all/gha2db_sync: columns
> 2024-02-27 15:30:09 all/gha2db_sync: columns ... 57.482705992s
> 2024-02-27 15:30:09 all/gha2db_sync: vars
> 2024-02-27 15:30:09 all/gha2db_sync: Environment Override: map[GHA2DB_VARS_FN_YAML:sync_vars.yaml]
> 2024-02-27 15:30:34 all/gha2db_sync: vars ... 25.610909091s
> 2024-02-27 15:30:34 all/gha2db_sync: Sync success
> 2024-02-27 15:30:34 all/gha2db_sync: gha2db_sync.go: error closing the connection: write tcp 192.168.193.218:53216->192.168.193.209:5432: write: broken pipe, sleeping for 300s to retry
> 2024-02-27 15:35:34 all/gha2db_sync: Time: 7h23m55.867787426s
> setting provisioned flag on 'allprj' database
> INSERT 0 1
> database 'allprj' marked as provisioned
> All affiliations updated
> Exit handler, final status is '0'
> setting provisioned flag on 'allprj' database
> INSERT 0 0
> database 'allprj' marked as provisioned
> clearing affs_lock flag on 'allprj' database
> DELETE 1
> database 'allprj' affs_lock flag cleared
> clearing affs_lock_all flag on 'devstats' database
> DELETE 1
> database 'devstats' affs_lock_all flag cleared
> ```
> 
> Just LMK then if there is still any action needed for Friday/weekend?

This looks good for now , need to add more data from my organizations will raise the PR by this week get it updated . Thanks you once again for your details and help

**Comment by lukaszgryglicki** [comment]
OK, thx.

**Pull request merged**
