### PR TITLE
Update developer affiliation for @swiatekm

### PR DESCRIPTION
**Pull request by swiatekm**
My account username was changed from `swiatekm-sumo` to `swiatekm` in the meantime. From what I understand about how this data is processed, I think just changing it in the dev files should give the right result. Please let me know if that's not the case and if I need to change anything else.

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
I will also do post merge updates as we track "history" so I need to have that data on the historical email as well.
Unless you really want to have your historical github account to be unrecognized for the past contributions?

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by swiatekm** [comment]
> I will also do post merge updates as we track "history" so I need to have that data on the historical email as well.
> Unless you really want to have your historical github account to be unrecognized for the past contributions?

Yeah, I'd like all of my contributions to be associated with my new account name.

**Comment by lukaszgryglicki** [comment]
So, I've already handled this in post-merge.
Thanks for confirming.

**Pull request merged**
