### PR TITLE
fix outdated affiliations of dixudx

### PR DESCRIPTION
**Pull request by dixudx**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Hi, you only need to update `developers_affiliationsN.txt` file(s) not `company_developersN.txt`.
I also see that you removed an email - is this because it is no longer current (but it was yours) or is this because it was never yours?
In the first case we need to keep it, so we can track historical contributions using thsi email.
@dixudx

**Comment by dixudx** [comment]
> I also see that you removed an email - is this because it is no longer current (but it was yours) or is this because it was never yours?
> In the first case we need to keep it, so we can track historical contributions using thsi email.

Used to be my account. But now that email is deprecated.

**Comment by lukaszgryglicki** [comment]
OK, but DevStats uses GitHub *archives* so data it processes comes from the past (it was archived on a given day/hour) so you contributions from the past will use your past email. We are supposed to track all emails, including historical ones. Can you add it back pelase and remove changes to `company_developerN.txt` files?

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
Will add this email back in post-merge.

**Pull request merged**
