### PR TITLE
Update developers_affiliations5.txt

### PR DESCRIPTION
**Pull request by mudit-01**
Removed affiliation for Mudit

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
You just want to remove from JSON/configs or you want to add those details to so-called forbiden list?
Askign because just removing will make that data reappear in the future.
If you want permanent delete - let me know I will handle this.

**Comment by mudit-01** [comment]
Hi @lukaszgryglicki  I want to remove the affiliation and become an Independent contributor please guide how to do that>

**Comment by lukaszgryglicki** [comment]
Well you just add end date on current affiliation and add a new one with independent. I will do it for you and let you know.

**Comment by mudit-01** [comment]
Thanks, @lukaszgryglicki

**Comment by lukaszgryglicki** [comment]
Data updated.

**Pull request closed without merging**
