### PR TITLE
Update affiliation (mjudeikis)

### PR DESCRIPTION
**Pull request by mjudeikis**
Move @mjudeikis out of RedHat to a new home :)

### CODE REVIEW

**Comment by mjudeikis** [comment]
How this PR feels: 
image

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by benjaminapetersen** [comment]
I'm a bit confused by this PR as the README indicates only edit `developer_affiliations*.txt` files as the `company_developers*.txt` files are generated.

**Comment by lukaszgryglicki** [comment]
I'm merging PRs and then usually running other automatic scripts that update many more places in addition to developers* compainies* - like JSONs, config files, etc.

**Pull request merged**
