### PR TITLE
Affiliate bryantbiggs with Amazon

### PR DESCRIPTION
**Pull request by bryantbiggs**
Affiliate @bryantbiggs with Amazon

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
@bryantbiggs are you sure want to update your affiliations to just two (Independent and AWS)?
because we already have such in our [JSON](https://github.com/cncf/gitdm/blob/master/src/github_users.json):
```
  {
    "login": "bryantbiggs",
    "email": "bryantbiggs!gmail.com",
    "affiliation": "Saint-Gobain < 2017-11-01, Independent < 2018-04-01, Xaxis < 2019-02-01, Frame < 2019-09-01, 2nd Watch < 2020-06-01, Caylent < 2021-08-01, Allergan < 2021-10-01, Clowd Haus < 2022-03-01, AWS",
    "source": "manual",
    "name": "Bryant Biggs",
    "commits": 10,
    "location": "NYC",
    "country_id": "us"
  },
  {
    "login": "bryantbiggs",
    "email": "bryantbiggs!users.noreply.github.com",
    "affiliation": "Saint-Gobain < 2017-11-01, Independent < 2018-04-01, Xaxis < 2019-02-01, Frame < 2019-09-01, 2nd Watch < 2020-06-01, Caylent < 2021-08-01, Allergan < 2021-10-01, Clowd Haus < 2022-03-01, AWS",
    "source": "manual",
    "name": "Bryant Biggs",
    "commits": 10,
    "location": "NYC",
    "country_id": "us"
  },
```

You added your affs in `developer_affiliations1.txt` as:
```
bryantbiggs: bryantbiggs!users.noreply.github.com, brybiggs!amazon.com, bryantbiggs!gmail.com, bryantbiggs!clowd.haus
  Independent until 2022-03-28
  Amazon from 2022-03-28
```

(but note that users below and above are from upper-case `B` not lower case `b`.
Your entry was already there in ``developer_affiliations3.txt`:
```
bryantbiggs: bryantbiggs!gmail.com, bryantbiggs!users.noreply.github.com
  Saint-Gobain until 2017-11-01
  Independent from 2017-11-01 until 2018-04-01
  Xaxis from 2018-04-01 until 2019-02-01
  Frame from 2019-02-01 until 2019-09-01
  2nd Watch from 2019-09-01 until 2020-06-01
  Caylent from 2020-06-01 until 2021-08-01
  Allergan from 2021-08-01 until 2021-10-01
  Clowd Haus from 2021-10-01 until 2022-03-01
  AWS from 2022-03-01
```

Was it bad? Maybe you can consider updating/fixing that one instead? It looks similar - the last one is AWS and start date is quite similar, whiule we have a lot richer history...
See [here](https://github.com/cncf/gitdm/blob/master/developers_affiliations3.txt#L924-L933) @bryantbiggs

**Comment by lukaszgryglicki** [comment]
For now I've included your 4 email addresses and a company list that I already had, but changed last one's end date from:
```
Clowd Haus from 2021-10-01 until 2022-03-01
AWS from 2022-03-01
```
to:
```
Clowd Haus from 2021-10-01 until 2022-03-28
AWS from 2022-03-28
```

please LMK if you want just 2 entries as you liste din your PR - no need to create another one, just LMK, I'll update manually then.
@bryantbiggs

**Comment by bryantbiggs** [comment]
oh, apologies - I didn't remember adding an affiliation before. This one looks good to me https://github.com/cncf/gitdm/blob/63114a2866265630fb6f60dd2e2b21016b1882dc/developers_affiliations3.txt#L1076-L1085 - sorry for the troubles!

**Comment by lukaszgryglicki** [comment]
Hey, thanks!
We are constantly researching this ourselves, so it was not you who added that one.
All clear, thanks.

**Pull request merged**
