### PR TITLE
Update affiliation for Karthik-k-n

### PR DESCRIPTION
**Pull request by Karthik-K-N**

### CODE REVIEW

**Comment by Karthik-K-N** [comment]
Do I need to update all the other files where my name is incorrectly added, for example https://github.com/cncf/gitdm/blob/master/company_developers2.txt#L11392. or will get update automatically?

**Comment by lukaszgryglicki** [comment]
No I will regenerate everything, you only need to modify files [mentioned here](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation).

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by Karthik-K-N** [comment]
Thank you, I could see my name only in [developers_affiliations1.txt](https://github.com/cncf/gitdm/pull/351/files#diff-b42fb989c1cad5682b2c424bae287510b976843f73a75509160c18e430fb687e) file.

But interestingly my name is updated against various companies I never been part of, Not sure how this might have happened.

**Comment by lukaszgryglicki** [comment]
I've merged & regenerated files.

**Pull request merged**
