### PR TITLE
Update my info (antweiss) in developers_affiliations2.txt

### PR DESCRIPTION
**Pull request by antweiss**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Hi, I see you've removed the "anton.weiss!naturalint.com" email - is this because it is no longer current or it never belonged to you?
Asking because we need to keep historical emails, because we track history.

**Comment by antweiss** [comment]
It's no longer current and I don't want this affiliation. But it's ok to keep it if necessary. Not such a big deal.

**Comment by lukaszgryglicki** [comment]
If you don't want to keep then no problem, I can merge, but if this is OK to keep it then I'll merge and restorer it in post-merge.

**Comment by antweiss** [comment]
ok to keep it. thank you @lukaszgryglicki

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Pull request merged**
