### PR TITLE
Update developers_affiliations2.txt

### PR DESCRIPTION
**Pull request by austinlparker**

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
Actually the Company name comes from a mapping file,so I think it will be changed back to what it was.
Is the ocmpany name incorrect? If so let me know the exact name that I should use in mapping instead.

**Comment by austinlparker** [comment]
Honeycomb and Hound Technology are the same thing - I thought Honeycomb mapped to Hound, and Hound is what shows up in devstats?

**Comment by lukaszgryglicki** [comment]
DevStats uses `Hound Technology Inc. dba Honeycomb` - I'll check for `Hound` and make sure it maps to the same and confirm here.

**Comment by lukaszgryglicki** [comment]
Just checked and there is no `Hound`, we only have `MediaHound`, `DraftHound`, `InfoHounds`, GREYHOUND` and `SoundHound` which containe that name, so mapping is correct IMHO - correct me if I'm wrong. 

`Hound Technology Inc. dba Honeycomb` is by far used the biggest number of contributors, also this mapping applies (changes name from A to B):
```
"Honeycomb": "Hound Technology Inc. dba Honeycomb"
```
There are no other mappings defined with a `Hound` in their names.

**Pull request merged**
