### PR TITLE
Update developers_affiliations6.txt

### PR DESCRIPTION
**Pull request by paulofrazao**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Hi, are you removing emails and company because it is not yours/never been yours *or* because it is no longer current?

Asking because if this wasn't yours at any time then this is OK, but if this was yours and is no longer current, then we want to keep the full history as this tool is parsing archival records using gharchives.com - so it "sees" data is it was in the past and we need all current and historical emails/affiliations.

**Comment by paulofrazao** [comment]
I am changing because it is no longer current.

**Comment by lukaszgryglicki** [comment]
I'll TAL again on Friday.

**Comment by lukaszgryglicki** [comment]
Ok so if it is no longer current (but was yours) it should stay - as we want all current & historical emails to be included.

**Comment by paulofrazao** [comment]
I updated it to have my full history. Hope this is enough.

**Comment by lukaszgryglicki** [comment]
Yes, this is fine, will merge on Monday.

**Review by lukaszgryglicki — APPROVED** [review]

**Pull request merged**
