### PR TITLE
update email for IRONICBo

### PR DESCRIPTION
**Pull request by IRONICBo**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Is this because this email (removed) is no longer current, or it was incorrect? Asking because we need to have both current and historical email to track past contributions.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by IRONICBo** [comment]
> no longer current

@lukaszgryglicki Sorry for my late reply, this email is wrong.

**Comment by lukaszgryglicki** [comment]
OK, thanks.

**Pull request merged**
