### PR TITLE
updated my gitdm affiliation detail

### PR DESCRIPTION
**Pull request by pranav-pandey0804**
Please update my affiliation details

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Is this a GitHub account rename or the original name was never correct?
Asking because if this is a rename then we need to keep both because we are parsing past data as saved in GitHub archives so it will contain both the old and new usernames.

**Comment by pranav-pandey0804** [comment]
> Is this a GitHub account rename or the original name was never correct? Asking because if this is a rename then we need to keep both because we are parsing past data as saved in GitHub archives so it will contain both the old and new usernames.

the name wasn't correct

**Comment by lukaszgryglicki** [comment]
Ok, so I will fix it as requested. Thanks!

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Pull request merged**
