### PR TITLE
Yahoo! Japan is not a part of Yahoo! Inc.

### PR DESCRIPTION
**Pull request by koba1t**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
I'm not sure what you want to achieve because in different files you are mapping to a different name. Can you just let me know what company name(s) should be changed to what? Just write a post here - and I will update the mapping and data files.

**Comment by koba1t** [comment]
@lukaszgryglicki 
> I'm not sure what you want to achieve because in different files you are mapping to a different name. Can you just let me know what company name(s) should be changed to what? Just write a post here - and I will update the mapping and data files.

Oh, Sorry... I don't understand how to edit these files.
I just want to divide the mapping of `Yahoo! Japan` from `Yahoo!`.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm - so I'm assuming this is to split out `Yahoo Japan!` from `Yahoo!`, right?

**Comment by lukaszgryglicki** [comment]
I'm closing this as I did updates manually.

**Comment by koba1t** [comment]
> so I'm assuming this is to split out Yahoo Japan! from Yahoo!, right?

That is right!
Thanks!

**Pull request closed without merging**
