### PR TITLE
Update github_users data Seo-yul

### PR DESCRIPTION
**Pull request by Seo-yul**
I just want to add country information to my account.
I don't want to add company or company information.

In this case, is it ok ..? just modify the github_user file only.

### CODE REVIEW

**Comment by Seo-yul** [comment]
line 129450
```
  {
    "login": "Seo-yul",
    "email": "Seo-yul!users.noreply.github.com",
    "affiliation": "",
    "source": "manual",
    "name": "Yoon Seo-yul",
    "commits": 152,
    "location": "South Korea",
    "country_id": "kr"
  },
```

**Comment by lukaszgryglicki** [comment]
THis is OK, I will do it manually and close this PR.

**Comment by Seo-yul** [comment]
> THis is OK, I will do it manually and close this PR.

Thank you for your confirmation.

**Comment by Seo-yul** [comment]
@lukaszgryglicki
Hi, I checked the `k8s.devstats.cncf.io` dashboard and I still don't have a country in my info. You can only see statistics in the country All, and you can't see my information in the `Korea Republic of` filter.
What should I do?

Thank you for your maintenance.

**Comment by lukaszgryglicki** [comment]
Affiliations data is imported once per 4 weeks, you just need to wait.

**Pull request closed without merging**
