### PR TITLE
remove incorrect affiliations from my history

### PR DESCRIPTION
**Pull request by thaJeztah**
I was listed as having been affiliated by various companies that I never worked for; let's remove those :)

Also trying to update my e-mail address (and associating some other addresses that may be used by me)

### CODE REVIEW

**Comment by thaJeztah** [comment]
Hope I'm doing this ok; I wasn't sure how to validate locally (tried running the scripts, and they didn't seem to work, but perhaps I'm holding it wrong)

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm - all looking good, but I will check why your user was listed twice, your PR is perfectly OK - if there is any issue, I will fix in the post-merge

**Comment by thaJeztah** [comment]
Thanks! Yes, I noticed this some Years back; https://twitter.com/thaJeztah/status/1474353712873283598?s=20

And it came up again in some discussion, when I realised I never opened a PR to fix it.

I found some other CSVs in this repo with data that could use some potential touch-ups, but honestly I wasn't sure which files exactly were fine to manually correct, and which ones are generated (I tried running some of the scripts but couldn't get them to work locally, so reduced the changes in this PR to be on the safe side)

**Comment by thaJeztah** [comment]
@lukaszgryglicki I just noticed a glitch in the "v3" presentation, where I see both `Docker` and `Docker Inc.` listed separately; is that something I can fix in this repository, or is that something that needs to be fixed elsewhere?

https://insights.v3.lfx.linuxfoundation.org/foundation/cncf/reports/organizations?project=containerd&bestPractice=false&repository=all&dateFilters=Last%207%20Days&dateRange=2023-09-09%20to%202023-09-15&compare=PP&granularity=day&hideBots=true

Screenshot 2023-09-15 at 09 19 41

**Comment by lukaszgryglicki** [comment]
This is for `DevStats`, Insights V3 does not have any public repos, you need to reach out to the V3 team using other means.
In `DevStats` they both are merged into one: https://github.com/cncf/gitdm/blob/master/src/mapping.json#L994.

**Comment by thaJeztah** [comment]
Thanks! I think I saw someone post an e-mail address for feedback, so let me send it there 👍

**Comment by lukaszgryglicki** [comment]
I would ask Insights V3 to open-source their repos.

**Comment by thaJeztah** [comment]
Yes, perhaps I should ask that as well; I wasn't sure if that was "temporary" (don't open it up, because it's still heavily in progress) or meant to be proprietary.

I _hope_ it's the former, as it'd be somewhat surprising for an "all open-source" organisation to do proprietary things, but 🤷‍♂️

**Comment by lukaszgryglicki** [comment]
Well not me to ask, I'm 2nd to vote that everything that LF does should be open source - the 1st thing that comes to my mind after "the linux foundation" is "open source", "linux".

**Pull request merged**
