### PR TITLE
Update affiliation for killianmuldoon

### PR DESCRIPTION
**Pull request by killianmuldoon**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Hi, why removing emails? Are they incorrect (not belonging to you) or maybe historical? We need to keep historical so we can parse past data - so you don't need to remove them, but if they were never yours then remove them of course.
I'll keep this open, please let me know which one is the case here.

**Comment by lukaszgryglicki** [comment]
I will be regenerating data now after 8 other PRs merged and with your 4 emails mentioned, please TAL in 15 minutes from now or later and eventually do fixes after that, please keep historical email but remove any that was never yours. If you want to remove any emails that are yours (like you don't want them to be processed at all - let me know - I will then add them to the so-called "forbidden list" and they will not appear anymore in any file in this repo and DevStats).

**Comment by killianmuldoon** [comment]
> Hi, why removing emails? Are they incorrect (not belonging to you) or maybe historical? We need to keep historical so we can parse past data - so you don't need to remove them, but if they were never yours then remove them of course.
I'll keep this open, please let me know which one is the case here.

These are historical - I'll update the PR to just add those emails.

**Comment by lukaszgryglicki** [comment]
Sure, will just merge in another batch. Check what is there now, maybe I just guessed right already...

**Comment by killianmuldoon** [comment]
Looks good - I guess it's fine to close this PR then?

**Comment by lukaszgryglicki** [comment]
Yep, closing then - I just guess-worked from the data you provided, thanks!

**Comment by killianmuldoon** [comment]
Thanks!

**Pull request closed without merging**
