### PR TITLE
Update imrajdas to dev affiliations

### PR DESCRIPTION
**Pull request by imrajdas**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Why you remove entry for another GitHub user name? Idf this is because you changed GitHub username then we need to keep old, because we're processing GitHub archives, so we see state from when given event happened, not current state, both your user name will be needed then.

**Comment by lukaszgryglicki** [comment]
@imrajdas ?

**Comment by imrajdas** [comment]
Hi @lukaszgryglicki , Appologies for the late reply. rajdas98 is my old username, I have reverted the rajdas98 changes

**Comment by lukaszgryglicki** [comment]
OK great, so this just adds a new username. Thanks!

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Pull request merged**
